### ISSUE TITLE
Stay at home and show deaths toggles misbehave

### ISSUE THREAD

**Issue by WisdomPill** [noiapp/covid-19-spread-simulator#25]
Simulation starts right when "stay at home" or "show deaths" is toggled.

After that the simulation appears to go on indefinitely.

I would argue also that the "show deaths" toggle is not needed as per se it is one of the main reasons to run a simulation in the first place

**Comment by brushtyler** [comment]
@WisdomPill The issue has been fixed yet (see #15)
