### ISSUE TITLE
added sidepanel configuration

### ISSUE THREAD

**Issue by marcopierobon** [noiapp/covid-19-spread-simulator#6]
**feature: Start simulator only on demand**

Scenario1: do not start automatically
As a user of the application
When I've open the app
Then the app is not running automatically

Scenario2: start on demand
As a user of the application
Given I've opened the app
When I press on Start
Then the app runs to completion

Scenario3: rerun on demand
As a user of the application
When I've run the app
Then the app allows me to trigger a new run

**feature: Disable checkboxes/dropdowns while the simulator is running**
Scenario1: checkboxes/dropdowns available when the app has not started
As a user of the application
When I've opened the app
Then checkboxes/dropdowns are not disabled

Scenario2: checkboxes/dropdowns disable once the app has started
As a user of the application
When I've opened the app
When I launch the simulation
Then checkboxes/dropdowns are disabled

Scenario3: checkboxes/dropdowns enabled once the simulation has completed
As a user of the application
When I've completed the run of the simulation 
Then checkboxes/dropdowns are enabled again

**feature: Add tooltips detailing what each field is meant to represent**
Scenario1: visibly recognise the items with a tooltip
As a user of the application
When I'm on the starting screen
Then I can see which fields support the dropdown by seeing them as having dotted underwriting

Scenario2: trigger the tooltip
As a user of the application
Given I'm on the starting screen
When I over a field that is signaled as having a tooltip
Then a tooltip appears detailing the meaning of the field

**feature: Add tooltips detailing what each field is meant to represent
Add sidepanels to control the following options:
Initial number of people
Initial number of people infected
Initial number of people using the app (%)
maximum speed (1-100%)**
Scenario1: run with default values
As a user of the application
Given I'm on the starting screen
When I click on run
Then the application runs with the selected settings

Scenario2: edit the total number of people
As a user of the application
Given I'm on the starting screen
And I've changed the total number of people
Then the number of displayed balls changes accordingly
And the graph displaying the evolution over time changes its height accordingly (1px per person)
And the states are updated correctly 
And the states are always summing to the total number of people
And none of states is ever negative

Scenario3: edit the Initial number of people infected
As a user of the application
Given I'm on the starting screen
And I've changed the Initial number of people infected
Then the number of displayed balls representing infected people changes accordingly
And the graph displaying the evolution over time changes its height accordingly (1px per person)
And the states are updated correctly 
And the states are always summing to the total number of people
And none of states is ever negative

Scenario4: edit the Initial number of people using the app (%)
As a user of the application
Given I'm on the starting screen
And I've changed the Initial number of people using the app (%)
Then the number of displayed balls representing people using the app changes accordingly
And the graph displaying the evolution over time changes its height accordingly (1px per person)
And the states are updated correctly 
And the states are always summing to the total number of people
And none of states is ever negative

Scenario5: edit the maximum speed (1-100%)
As a user of the application
Given I'm on the starting screen
And I've changed the maximum speed (1-100%)**
Then the speed of the balls changes accordingly

**feature: Make the layout compatible with mobile devices (although a further issue should be raised)**
Scenario1: Visualise the app with an Ipad simulator in landscape mode
As a user of the application
Given I'm on the starting screen with an Ipad
Then I can run the simulator on landscape mode

Scenario2: Visualise the app with an Ipad simulator in vertical mode
As a user of the application
Given I'm on the starting screen with an Ipad
Then I can run the simulator on vertical mode

Scenario3: Visualise the app with an IPhoneX simulator in landscape mode
As a user of the application
Given I'm on the starting screen with an IPhoneX 
Then I can run the simulator on landscape mode

Scenario4: Visualise the app with an IPhoneX simulator in vertical mode
As a user of the application
Given I'm on the starting screen with an IPhoneX 
Then I can run the simulator on vertical mode

Scenario5: Visualise the app with an Galaxy S5 simulator in landscape mode
As a user of the application
Given I'm on the starting screen with an  Galaxy S5 
Then I can run the simulator on landscape mode

Scenario6: Visualise the app with an  Galaxy S5 simulator in vertical mode
As a user of the application
Given I'm on the starting screen with an  Galaxy S5 
Then I can run the simulator on vertical mode

**Comment by brushtyler** [comment]
Well done. The PR #3 has been merged.
